### PR TITLE
Icon Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The [eOS HIG](https://elementary.io/docs/human-interface-guidelines#shape) specifically stated to avoid unnecessary base shape. As such, in my opinion, the icon you're using has unnecessary base shape. I have designed a lock without base shape. Any criticism?

### CODE REVIEW

**Comment by arshubham** [comment]
@Fatih20 Thanks for the contribution. Don't have access to elementary machine for a few days. Will test and get back to you.

**Comment by Fatih20** [comment]
Um no, according to the [eOS HIG](https://elementary.io/docs/human-interface-guidelines#size) the icon should be pixel-fitted meaning that the smaller size is not just a downscale of the larger. Instead, ideally, they are designed differently because at smaller sizes, certain elements are not visible or they will just be a blurred pixel at smaller size.

**Comment by NathanBnm** [comment]
Okay, never seen that before :thinking:

**Comment by Fatih20** [comment]
So, how's it? @arshubham

**Comment by arshubham** [comment]
@Fatih20 Thanks for the contribution. I like the icons. However I have one issue with it. The Asterisks are not shown in the icons when installed. 
image

They are shown when opened with inkscape or exporting to PNG. Can you tell me why is it happening? Also please replace the PNG file with your icon: https://github.com/arshubham/cipher/blob/master/data/images/com.github.arshubham.cipher.png

**Comment by Fatih20** [comment]
It seems there are some issues on my end. I'll fix it in a sec.

**Comment by arshubham** [comment]
@Fatih20  Thanks looks great now. While I have you here Can you also look into https://github.com/arshubham/gitignore/pull/19 I had to revert it due to background issue.

**Comment by Fatih20** [comment]
Can you credit me in the contributors file and the release notes?

**Comment by arshubham** [comment]
Sure will do that

**Comment by Fatih20** [comment]
In case you're curious, here's a video of me making the icon.
https://open.lbry.com/@Fatih109:4/Cipher:9?r=Cg1pp5MCWV1a5Nj5jDumPs9b13dNZqWG

**Pull request merged**
